import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/Common/Layout';
import Navbar from '../components/Navbar';
import Section1 from './Landing/Components/Section1';
import Section2 from './Landing/Components/Section2';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Andio Rio Gallegos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Layout>
        <Section1 />
      </Layout>

      <Section2 />
    </div>
  );
};

export default Home;
